language: cpp

compiler: clang

os: osx
osx_image: xcode6.4

before_install: true

install: true

script:
  - rm /usr/local/include/c++
  - brew update
  - brew upgrade
  - brew tap homebrew/science
  - brew install -v triqs.rb --with-test
