language: cpp

os: osx
osx_image: xcode8.3

before_install: true

install: true

script:
  - brew remove --force $(brew list) --ignore-dependencies  
  - brew update
  - brew tap homebrew/science
  - brew install triqs.rb
