language: cpp

compiler: clang

os: osx
osx_image: 
  - xcode8.3
  - xcode8
  - xcode7.3
  - xcode6.4

before_install: true

install: true

script:
  - rm /usr/local/include/c++
  - brew update
  - brew upgrade
  - brew tap homebrew/science
  - brew install triqs.rb --with-test
